x-common: &common-setup
  image: fabook/control:0.0.1
  network_mode: host
  privileged: true
  volumes: 
    - ${HOME}/.Xauthority:/home/mobile/.Xauthority:rw
    - .:/home/ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw

  environment:
    - "DISPLAY"
    - "QT_X11_NO_MITSHM=1"
  ports:
    - "9090:9090"
  entrypoint: >
    bash -c "
    /bin/bash
    "

services:
  terminal:
    <<: *common-setup
    stdin_open: true  # docker run -i
    tty: true        # docker run -t
    working_dir: /home/ws
    command: []

  get_docs:
    <<: *common-setup
    # TODO
    working_dir: /home/ws/src
    stdin_open: true  # docker run -i
    tty: true        # docker run -t
    entrypoint: >
      bash -c "
        echo 'Starting' &&
        ./scripts/get_docs.sh
      "

  test:
    <<: *common-setup
    # TODO
    working_dir: /home/ws/src
    stdin_open: true  # docker run -i
    tty: true        # docker run -t
    entrypoint: >
      bash -c "
        echo 'Starting' &&
        python3 python_lib/src/inno_control/core.py
      "
