name: Code Quality Check

on:
  push:
    paths:
      - 'inno_control/**'
      - 'firmware/**'
  pull_request:
    paths:
      - 'inno_control/**'
      - 'firmware/**'
  workflow_dispatch:

jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
          
      - name: Install tools
        run: pip install black pydocstyle

      - name: Run Black formatting check
        run: black --check inno_control/ --config pyproject.toml
        
      - name: Run docstring check
        run: pydocstyle inno_control/ --config .pydocstyle

  cpp-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format-14
      
      - name: Check C++ formatting
        run: |
          cd firmware
          find main -type f \( -name '*.c' -o -name '*.h' \) \
          -exec clang-format-14 --style=file --dry-run --Werror {} \;